name: Robot Framework E2E -tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_application:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Frontend Dependencies
        working-directory: app-frontend
        run: npm ci

      - name: Build Frontend
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
        working-directory: app-frontend
        run: npm run build

      - name: Install Backend Dependencies and Build Backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLERK_WEBHOOK_SIGNING_SECRET: ${{ secrets.CLERK_WEBHOOK_SIGNING_SECRET }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
        working-directory: app-backend
        run: npm run deploy-ci

      - name: Upload Build Artifacts 
        uses: actions/upload-artifact@v4 
        with: 
          name: build 
          path: | 
            app-frontend/dist
            app-backend/dist



  robot_tests:
    runs-on: ubuntu-latest
    needs: build_application

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Backend Dependencies
        working-directory: app-backend
        run: npm ci

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser

      - name: Initialize Browser (Chromium)
        run: |
          rfbrowser init chromium
      
      - name: Start Backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CLERK_WEBHOOK_SIGNING_SECRET: ${{ secrets.CLERK_WEBHOOK_SIGNING_SECRET }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
        working-directory: app-backend
        run: |
          nohup npm run start &

      - name: Run Robot Framework Tests
        env:
          URL: ${{ secrets.APP_URL }}
          USERNAME: ${{ secrets.TESTUSER_NAME }}
          PASSWORD: ${{ secrets.TESTUSER_PASSWORD }}
        run: |
          robot robotframework-tests/tests
      
      - name: Upload Robot Framework Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: |
            output.xml
            log.html
            report.html

      - name: Delete Build Artifact (needed only for sharing between jobs)
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build
